language: java
notifications:
  email:
    - daniel@thinkaurelius.com
jdk:
  - oraclejdk7
  - oraclejdk8
env:
 - MAVEN_OPTS='-Dtp.version=3'
 - MAVEN_OPTS='-Dtp.version=2'
branches:
  only:
    - master
